#!/bin/bash

repos=(
	"brianwells-recipes"
	"grahampugh/jamf-upload"
	"grahampugh-recipes"
	"hansen-m-recipes"
	"hjuutilainen-recipes"
	"homebysix-recipes"
	"jleggat-recipes"
	"jps3-recipes"
	"recipes"
	"rtrouton-recipes"
	"scriptingosx-recipes"
	"https://github.com/jchutc0/autopkg-uploaders"
)

overrides=(
	"AutoPkg.jamf-upload"
	"BBEdit.jamf-upload"
	"Blender.jamf-upload"
	"EndNote21.jamf-upload"
	"Fetch.jamf-upload"
	"Firefox.jamf-upload"
	"GoogleChrome.jamf-upload"
	"MicrosoftAutoUpdate.jamf-upload"
	"MicrosoftDefenderATP.jamf-upload"
	"MicrosoftOffice365BusinessProSuite.jamf-upload.recipe"
	"MicrosoftOneDrive.jamf-upload"
	"MicrosoftTeamsForWorkOrSchool.jamf-upload.recipe"
	"Privileges.jamf-upload"
	"SigniantApp.jamf-upload"
	"Skype.jamf-upload"
	"SwiftLint.jamf-upload"
	"VLC.jamf-upload"
	"VueScan.jamf-upload"
	"Zoom.jamf-upload"
	"swiftDialog.jamf-upload"
)
